apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: connectmoda-staging

resources:
  - ../../base
  - ../../apps/api
  - ../../apps/worker
  - ../../apps/gateway

patches:
  - path: replicas-patch.yaml
  - path: env-patch.yaml
